# Generated by Django 4.2.1 on 2023-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID Пользователя')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя Пользователя')),
                ('user_target', models.TextField(verbose_name='Цель пользователя')),
                ('user_image', models.ImageField(upload_to='user_image/', verbose_name='Фотография пользователя')),
                ('user_gender', models.CharField(max_length=255, verbose_name='Пол пользователя')),
                ('user_age', models.IntegerField(verbose_name='Возраст пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
    ]
